"""Adverse-action notice rendering scaffold."""

from __future__ import annotations

from datetime import datetime
from typing import Any


def render_adverse_action_notice(
    customer_name: str,
    quote_id: str,
    jurisdiction: str,
    reason_codes: list[str],
    details: dict[str, Any] | None = None,
) -> str:
    """Render a plain-text adverse-action notice draft.

    This is a scaffold. Production use requires jurisdiction-specific legal
    review, required disclosures, delivery tracking, and template versioning.
    """
    details = details or {}
    reasons = "\n".join(f"- {code}" for code in reason_codes) or "- Not specified"
    return f"""Adverse Action Notice Draft

Date: {datetime.utcnow().date().isoformat()}
Jurisdiction: {jurisdiction}
Customer: {customer_name}
Quote ID: {quote_id}

We are unable to proceed with this insurance transaction based on the following review codes:
{reasons}

Additional review details:
{details}

This notice is a draft generated by the insurance operating system. It must be reviewed against jurisdiction-specific requirements before delivery.
"""
