"""Policy packet rendering scaffold."""

from __future__ import annotations

from datetime import datetime
from typing import Any


def render_policy_packet(policy: dict[str, Any]) -> str:
    """Render a plain-text policy packet draft.

    This is a scaffold for audit/review. Production use requires filed forms,
    endorsements, declarations, legal review, and immutable template versions.
    """
    coverages = policy.get("coverages") or policy.get("bind_packet", {}).get("quote_snapshot", {}).get("coverages", {})
    coverage_lines = "\n".join(f"- {name}: {amount}" for name, amount in coverages.items()) or "- No coverage lines supplied"
    return f"""Policy Packet Draft

Generated At: {datetime.utcnow().isoformat()}Z
Policy ID: {policy.get('policy_id', 'pending')}
Quote ID: {policy.get('quote_id', 'unknown')}
State: {policy.get('state', 'draft')}
Effective Date: {policy.get('effective_date', 'unknown')}
Expiration Date: {policy.get('expiration_date', 'unknown')}
Total Premium: {policy.get('total_premium', 'unknown')}

Coverage Summary:
{coverage_lines}

This packet is a draft generated by the insurance operating system. It is not a filed policy form and must not be delivered as a real policy until approved templates are integrated.
"""
