"""Outbox pattern for reliable blockchain transaction submission.

The outbox ensures that audit events generated by the policy service
are reliably submitted to the blockchain, even in the face of failures.

Flow:
  1. Policy service generates an audit event -> inserts into outbox table
  2. Gateway poller picks up pending outbox entries -> submits to chain
  3. On success -> marks entry as committed
  4. On failure -> retries with backoff
"""

from __future__ import annotations

import json
import logging
import sqlite3
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

logger = logging.getLogger(__name__)


class OutboxStatus(str, Enum):
    PENDING = "pending"
    SUBMITTED = "submitted"
    COMMITTED = "committed"
    FAILED = "failed"


@dataclass
class OutboxEntry:
    """A pending blockchain transaction in the outbox."""
    id: str
    event_type: str
    payload: str  # JSON string of payload data
    contract: str  # "policy_registry" or "audit_event_registry"
    method: str  # "commitPolicy" or "recordEvent"
    status: str
    tx_hash: str | None
    retry_count: int
    last_error: str | None
    created_at: str
    updated_at: str
    next_retry_at: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "OutboxEntry":
        return cls(**d)

    @classmethod
    def from_row(cls, row: tuple) -> "OutboxEntry":
        keys = [
            "id", "event_type", "payload", "contract", "method",
            "status", "tx_hash", "retry_count", "last_error",
            "created_at", "updated_at", "next_retry_at",
        ]
        return cls(
            id=row[0],
            event_type=row[1],
            **json.loads(row[2]),
            contract=row[3],
            method=row[4],
            status=row[5],
            tx_hash=row[6],
            retry_count=row[7],
            last_error=row[8],
            created_at=row[9],
            updated_at=row[10],
            next_retry_at=row[11],
        )


class OutboxStore:
    """SQLite-backed outbox store for pending blockchain transactions."""

    def __init__(self, db_path: str):
        self.db_path = db_path
        self._init_db()

    def _init_db(self):
        """Create outbox table if it doesn't exist."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS outbox (
                    id TEXT PRIMARY KEY,
                    event_type TEXT NOT NULL,
                    payload TEXT NOT NULL,
                    contract TEXT NOT NULL,
                    method TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'pending',
                    tx_hash TEXT,
                    retry_count INTEGER NOT NULL DEFAULT 0,
                    last_error TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    next_retry_at TEXT
                )
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_outbox_status ON outbox(status)
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_outbox_retry ON outbox(next_retry_at)
            """)
            conn.commit()
        logger.info("Outbox store initialized: %s", self.db_path)

    def insert(self, entry: OutboxEntry) -> str:
        """Insert a pending outbox entry. Returns entry id."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                INSERT OR IGNORE INTO outbox (
                    id, event_type, payload, contract, method,
                    status, tx_hash, retry_count, last_error,
                    created_at, updated_at, next_retry_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                entry.id,
                entry.event_type,
                json.dumps(entry.to_dict()),
                entry.contract,
                entry.method,
                entry.status,
                entry.tx_hash,
                entry.retry_count,
                entry.last_error,
                entry.created_at,
                entry.updated_at,
                entry.next_retry_at,
            ))
            conn.commit()
        logger.info("Outbox entry created: %s", entry.id)
        return entry.id

    def get_pending_entries(self, limit: int = 50) -> list[OutboxEntry]:
        """Get pending outbox entries ready for retry."""
        now = datetime.now(timezone.utc).isoformat()
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT id, event_type, payload, contract, method,
                       status, tx_hash, retry_count, last_error,
                       created_at, updated_at, next_retry_at
                FROM outbox
                WHERE status IN ('pending', 'failed')
                  AND (next_retry_at IS NULL OR next_retry_at <= ?)
                ORDER BY retry_count ASC, created_at ASC
                LIMIT ?
            """, (now, limit))
            return [OutboxEntry.from_row(row) for row in cursor.fetchall()]

    def mark_submitted(self, entry_id: str, tx_hash: str) -> None:
        """Mark an entry as submitted (tx sent to chain)."""
        now = datetime.now(timezone.utc).isoformat()
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                UPDATE outbox
                SET status = 'submitted', tx_hash = ?, updated_at = ?
                WHERE id = ?
            """, (tx_hash, now, entry_id))
            conn.commit()

    def mark_committed(self, entry_id: str) -> None:
        """Mark an entry as committed on chain."""
        now = datetime.now(timezone.utc).isoformat()
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                UPDATE outbox
                SET status = 'committed', updated_at = ?
                WHERE id = ?
            """, (now, entry_id))
            conn.commit()

    def mark_failed(self, entry_id: str, error: str) -> None:
        """Mark an entry as failed with error message."""
        now = datetime.now(timezone.utc).isoformat()
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                UPDATE outbox
                SET status = 'failed',
                    retry_count = retry_count + 1,
                    last_error = ?,
                    updated_at = ?,
                    next_retry_at = datetime(
                        'now',
                        '+' || (
                            SELECT 2 * retry_count + 1
                            FROM outbox WHERE id = ?
                        ) || 'seconds'
                    )
                WHERE id = ?
            """, (error, now, entry_id, entry_id))
            conn.commit()

    def get_entry(self, entry_id: str) -> OutboxEntry | None:
        """Get a single outbox entry by ID."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT id, event_type, payload, contract, method,
                       status, tx_hash, retry_count, last_error,
                       created_at, updated_at, next_retry_at
                FROM outbox WHERE id = ?
            """, (entry_id,))
            row = cursor.fetchone()
            if row:
                return OutboxEntry.from_row(row)
            return None

    def get_pending_count(self) -> int:
        """Get count of pending entries."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT COUNT(*) FROM outbox
                WHERE status IN ('pending', 'failed')
            """)
            return cursor.fetchone()[0]

    def get_stats(self) -> dict[str, int]:
        """Get outbox statistics."""
        with sqlite3.connect(self.db_path) as conn:
            stats = {}
            for status in ["pending", "submitted", "committed", "failed"]:
                cursor = conn.execute(
                    "SELECT COUNT(*) FROM outbox WHERE status = ?",
                    (status,),
                )
                stats[status] = cursor.fetchone()[0]
            return stats
